baseURL = "http://example.org/"
languageCode = "en-us"
title = "Nginx Experience"

theme = "learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "green"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]

name = "AWS_S3_deployment"

URL = "s3://nginx-experience?region=eu-central-1"